NAME = fileutils
LIBRARY = true
CMO = version.cmo sysPath.cmo sysUtil.cmo 
REQUIRES = unix str 
PREDICATES = 
INSTALLIB = fileutils.a fileutils.cmxa fileutils.cma sysPath.cmi sysUtil.cmi META

include ../TopMakefile
